### ISSUE TITLE
Fuzzy matching instead of matching a prefix

### ISSUE THREAD

**Issue by samsonjs** [markohlebar/Peckham#12]
It would be great to be able to import, say, SDWebImageManager.h by typing "sdwim" rather than "SDWebImageM".

**Comment by ForrestAlfred** [comment]
Maybe fuzzy matching is a great feature, such as me with a lot of long name classes, with this feature I can only input few words to match the proper class.

**Comment by markohlebar** [comment]
@ForrestAlfred I started work on that a long time ago and never got around to finalize it. Will go back to take a look at the state of it and maybe finish it off quick.

**Comment by ClementPadovani** [comment]
Current [WIP], should be quick.

https://github.com/ClementPadovani/Peckham/tree/feature/fuzzySearch

**Comment by ClementPadovani** [comment]
Actually @markohlebar if you could have a look that’d be cool

**Comment by markohlebar** [comment]
@ClementPadovani this is cool! I think we can just ship it as a first version of fuzzy matching support. It would be awesome to add the highlighting as well. Also maybe a result that matches capitalization i.e. when I type `SAO` in search for `MHSearchArrayOperation` would be weighted as more relevant?

**Comment by ClementPadovani** [comment]
@markohlebar Yes, that’d be cool. However isn’t a little soon to ship?

There’s currently a test that’s failing due to the fuzzy-searching and the search results don’t render correctly.

**Comment by markohlebar** [comment]
@ClementPadovani shipped it already, if you use it as you usually would, there is no noticable difference. I'm currently working on rendering and highlights, hopefully will be done today 👍 also, I fixed that test.

**Comment by markohlebar** [comment]
@samsonjs @ClementPadovani I'm pretty happy with the results, check it out.

**Comment by ForrestAlfred** [comment]
Perfect

**Comment by ClementPadovani** [comment]
![untitled 2](https://cloud.githubusercontent.com/assets/676023/14978935/8761b7a6-111f-11e6-931c-87a8cdd68012.png)

Really impressed! Thanks!
