### ISSUE TITLE
profiling notices in Xcode7

### ISSUE THREAD

**Issue by basvankuijck** [markohlebar/Peckham#47]
Installed the plugin through Alcatraz

I'm running Xcode7 beta 4
And when I'm building any project (through either xcode, xctool or xcodebuild) I get a bunch of these messages:

    profiling: /Users/xxx/Library/Developer/Xcode/DerivedData/MHImportBuster-esjnphrkxbkayucmuszdhqdopppi/Build/Intermediates/MHImportBuster.build/Debug/MHImportBuster.build/Objects-normal/x86_64/MHHeaderCache.gcda: cannot merge previous GCDA file: corrupt arc tag (0x00000004)    
    profiling: /Users/xxx/Library/Developer/Xcode/DerivedData/MHImportBuster-esjnphrkxbkayucmuszdhqdopppi/Build/Intermediates/MHImportBuster.build/Debug/MHImportBuster.build/Objects-normal/x86_64/NSMutableIndexSet+NSArray.gcda: cannot merge previous run count: corrupt object tag (0x01000000)

Only disabling the plugin would resolve it

**Comment by markohlebar** [comment]
Hey @basvankuijck thanks for reporting... I'll take a look if same thing happens on my mac.

**Comment by basvankuijck** [comment]
Thanks!
They're just simple notices, so the build still succeeds. But my terminal is cluttered with these lines.

Sidenote: Thanks for plugin contribution, it really saves me a lot af scrolling ;)

**Comment by markohlebar** [comment]
Thanks man appreciate it :) I'll look into it anyway, it sounds like a nuisance.

**Comment by ClementPadovani** [comment]
I've fixed this issue by ignoring `.gcda` and `.gcno` files.

https://github.com/ClementPadovani/Peckham/commit/35d26b77e08b84a0480d8813e22f49191539dcd4

**Comment by ClementPadovani** [comment]
@markohlebar You can now close this issue.

**Comment by markohlebar** [comment]
@ClementPadovani cheers!
