### ISSUE TITLE
Xcode 7 not working

### ISSUE THREAD

**Issue by socoboy** [markohlebar/Peckham#64]
After build the code, I don't find the plugin in Xcode plugins directory. Beside, Command+Ctrl+P not working.

Could you delve further into it? This is very awesome plugin, and help me much when coding. 

Hope that it could be fixed soon.

Regards,
Tung

**Comment by markohlebar** [comment]
Hey @socoboy did you try to install using Alcatraz?

**Comment by markohlebar** [comment]
Also, send me the exact version of Xcode you are using.

**Comment by socoboy** [comment]
Hi, Thanks for your quickly reply. I'm not use Alcatraz to install, I just download the source code and build it. That way work on Xcode 6.3.

My Xcode version is Xcode 7 Version 7.0 (7A220), I download it from apple developer resource page. My Mac version is Yosemite 10.10.5 (14F27)

**Comment by ahknight** [comment]
Same here.  Though I wonder if this is related to having Xcode named "Xcode7" and "Xcode6" perhaps, since we both appear to have two versions installed?

**Comment by markohlebar** [comment]
@socoboy @ahknight  this should be fixed now.
