### ISSUE TITLE
Not working on Xcode 7.2.1

### ISSUE THREAD

**Issue by ftronnbe** [markohlebar/Peckham#77]

**Comment by markohlebar** [comment]
Hey @ftronnbe, I just tested on my machine with `7.2.1 (7C1002)` and it works fine.
Did you get asked to load additional bundles and pressed `NO`? 

This SO thread handles a lot of gotchas that can be encountered with plugins, so check it out and please let me know if any of it works. 

http://stackoverflow.com/questions/30361228/why-are-my-xcode-plugins-such-as-clang-format-installed-with-alcatraz-no-longe

**Comment by markohlebar** [comment]
Namely, try this `defaults read com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.2.1` and see if `Peckham` is in the allowed list.

**Comment by ftronnbe** [comment]
Thanks @markohlebar! I suspected a problem with Peckham since all my other plugins were working correctly after the Xcode update. I tried to reinstall the plugin using alcatraz but to no avail.

I then re-installed alcatraz and then re-installed Peckham. It is now working correctly.

**Comment by markohlebar** [comment]
@ftronnbe wow, that's strange that reinstalling both worked. Thanks for getting back with this, I'll add some troubleshooting section for posterity.
