### ISSUE TITLE
Cmd-Ctrl-P not working on macOS 10.11.6 with Xcode 8

### ISSUE THREAD

**Issue by itsdamslife** [markohlebar/Peckham#96]
Cmd-Ctrl-P is already assigned to Emoticon popups on 10.11. Hence Peckham stopped working on macOS 10.11.6. Any other alternative?

Thanks

**Comment by markohlebar** [comment]
Hi @itsdamslife, Peckham won't work on Xcode 8, you can read more about it [in my recent blog post](https://medium.com/@markohlebar/how-i-launched-my-open-source-project-976c312f087f), and then try using [Import](https://github.com/markohlebar/import) :)
